export const activeColumns = [
  {
    status: {
      id: 1,
      status: "CLIENT_IN_PROGRESS",
      label: "Clients in Progress",
    },
    deal: [
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
    ],
  },
  {
    status: {
      id: 1,
      status: "CLIENT_IN_PROGRESS",
      label: "Clients in Progress",
    },
    deal: [
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
    ],
  },
  {
    status: {
      id: 1,
      status: "CLIENT_IN_PROGRESS",
      label: "Clients in Progress",
    },
    deal: [
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
    ],
  },
  {
    status: {
      id: 1,
      status: "CLIENT_IN_PROGRESS",
      label: "Clients in Progress",
    },
    deal: [
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
    ],
  },
  {
    status: {
      id: 1,
      status: "CLIENT_IN_PROGRESS",
      label: "Clients in Progress",
    },
    deal: [
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
    ],
  },
  {
    status: {
      id: 1,
      status: "CLIENT_IN_PROGRESS",
      label: "Clients in Progress",
    },
    deal: [
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
    ],
  },
  {
    status: {
      id: 1,
      status: "CLIENT_IN_PROGRESS",
      label: "Clients in Progress",
    },
    deal: [
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
      {
        id: "134",
        name: "დათუნა ბასილაძე",
        amount: 134444,
        ccy: "GEL",
        product: "სამომხმარებლო სესხი",
      },
    ],
  },
];

export const deals = {
  content: [
    {
      id: "D2052",
      name: "ლაურსაბ თათქარიძე",
      personalId: "12345678910",
      mobilePhone: "512345678",
      channel: "bbcredit",
      product: "სამომხმარებლო სესხი",
      amount: 177000,
      ccy: "GEL",
      comment: null,
      createDate: "2024-07-22T00:19:00",
      owner: {
        externalId: "2a24c399-7bf0-4b1d-b8d8-4c42eac8f904",
        name: "john82",
        fullName: "John Doe",
        shortName: "JD",
      },
      dealStatus: "ACTIVE",
      tags: [],
      progressStatus: {
        id: 1,
        status: "CLIENTS_IN_PROGRESS",
        label: "Clients in Progress",
        order: 0,
      },
      progressSubStatus: null,
      leads: [
        {
          id: "L2852",
          name: "ლაურსაბ თათქარიძე",
          personalId: "12345678910",
          mobilePhone: "512345678",
          channel: "bbcredit",
          product: "სამომხმარებლო სესხი",
          amount: 177000,
          ccy: "GEL",
          createDate: "2024-07-22T00:19:00",
        },
      ],
    },
    {
      id: "D2050",
      name: "ლაურსაბ თათქარიძე",
      personalId: "12345678910",
      mobilePhone: "512345678",
      channel: "bbcredit",
      product: "სამომხმარებლო სესხი",
      amount: 177000,
      ccy: "GEL",
      comment: null,
      createDate: "2024-07-22T00:19:00",
      owner: {
        externalId: "2a24c399-7bf0-4b1d-b8d8-4c42eac8f904",
        name: "john82",
        fullName: "John Doe",
        shortName: "JD",
      },
      dealStatus: "ACTIVE",
      tags: [],
      progressStatus: {
        id: 1,
        status: "CLIENTS_IN_PROGRESS",
        label: "Clients in Progress",
        order: 0,
      },
      progressSubStatus: null,
      leads: [
        {
          id: "L2852",
          name: "ლაურსაბ თათქარიძე",
          personalId: "12345678910",
          mobilePhone: "512345678",
          channel: "bbcredit",
          product: "სამომხმარებლო სესხი",
          amount: 177000,
          ccy: "GEL",
          createDate: "2024-07-22T00:19:00",
        },
      ],
    },
    {
      id: "D2053",
      name: "ლაურსაბ თათქარიძე",
      personalId: "12345678910",
      mobilePhone: "512345678",
      channel: "bbcredit",
      product: "სამომხმარებლო სესხი",
      amount: 177000,
      ccy: "GEL",
      comment: null,
      createDate: "2024-07-22T00:19:00",
      owner: {
        externalId: "2a24c399-7bf0-4b1d-b8d8-4c42eac8f904",
        name: "john82",
        fullName: "John Doe",
        shortName: "JD",
      },
      dealStatus: "ACTIVE",
      tags: [],
      progressStatus: {
        id: 1,
        status: "CLIENTS_IN_PROGRESS",
        label: "Clients in Progress",
        order: 0,
      },
      progressSubStatus: null,
      leads: [
        {
          id: "L2852",
          name: "ლაურსაბ თათქარიძე",
          personalId: "12345678910",
          mobilePhone: "512345678",
          channel: "bbcredit",
          product: "სამომხმარებლო სესხი",
          amount: 177000,
          ccy: "GEL",
          createDate: "2024-07-22T00:19:00",
        },
      ],
    },
    {
      id: "D2054",
      name: "ლაურსაბ თათქარიძე",
      personalId: "12345678910",
      mobilePhone: "512345678",
      channel: "bbcredit",
      product: "სამომხმარებლო სესხი",
      amount: 177000,
      ccy: "GEL",
      comment: null,
      createDate: "2024-07-22T00:19:00",
      owner: {
        externalId: "2a24c399-7bf0-4b1d-b8d8-4c42eac8f904",
        name: "john82",
        fullName: "John Doe",
        shortName: "JD",
      },
      dealStatus: "ACTIVE",
      tags: [],
      progressStatus: {
        id: 1,
        status: "CLIENTS_IN_PROGRESS",
        label: "Clients in Progress",
        order: 0,
      },
      progressSubStatus: null,
      leads: [
        {
          id: "L2852",
          name: "ლაურსაბ თათქარიძე",
          personalId: "12345678910",
          mobilePhone: "512345678",
          channel: "bbcredit",
          product: "სამომხმარებლო სესხი",
          amount: 177000,
          ccy: "GEL",
          createDate: "2024-07-22T00:19:00",
        },
      ],
    },
    {
      id: "D2055",
      name: "ლაურსაბ თათქარიძე",
      personalId: "12345678910",
      mobilePhone: "512345678",
      channel: "bbcredit",
      product: "სამომხმარებლო სესხი",
      amount: 177000,
      ccy: "GEL",
      comment: null,
      createDate: "2024-07-22T00:19:00",
      owner: {
        externalId: "2a24c399-7bf0-4b1d-b8d8-4c42eac8f904",
        name: "john82",
        fullName: "John Doe",
        shortName: "JD",
      },
      dealStatus: "ACTIVE",
      tags: [],
      progressStatus: {
        id: 1,
        status: "CLIENTS_IN_PROGRESS",
        label: "Clients in Progress",
        order: 0,
      },
      progressSubStatus: null,
      leads: [
        {
          id: "L2852",
          name: "ლაურსაბ თათქარიძე",
          personalId: "12345678910",
          mobilePhone: "512345678",
          channel: "bbcredit",
          product: "სამომხმარებლო სესხი",
          amount: 177000,
          ccy: "GEL",
          createDate: "2024-07-22T00:19:00",
        },
      ],
    },
    {
      id: "D2056",
      name: "ლაურსაბ თათქარიძე",
      personalId: "12345678910",
      mobilePhone: "512345678",
      channel: "bbcredit",
      product: "სამომხმარებლო სესხი",
      amount: 177000,
      ccy: "GEL",
      comment: null,
      createDate: "2024-07-22T00:19:00",
      owner: {
        externalId: "2a24c399-7bf0-4b1d-b8d8-4c42eac8f904",
        name: "john82",
        fullName: "John Doe",
        shortName: "JD",
      },
      dealStatus: "ACTIVE",
      tags: [],
      progressStatus: {
        id: 1,
        status: "CLIENTS_IN_PROGRESS",
        label: "Clients in Progress",
        order: 0,
      },
      progressSubStatus: null,
      leads: [
        {
          id: "L2852",
          name: "ლაურსაბ თათქარიძე",
          personalId: "12345678910",
          mobilePhone: "512345678",
          channel: "bbcredit",
          product: "სამომხმარებლო სესხი",
          amount: 177000,
          ccy: "GEL",
          createDate: "2024-07-22T00:19:00",
        },
      ],
    },
    {
      id: "D2057",
      name: "ლაურსაბ თათქარიძე",
      personalId: "12345678910",
      mobilePhone: "512345678",
      channel: "bbcredit",
      product: "სამომხმარებლო სესხი",
      amount: 177000,
      ccy: "GEL",
      comment: null,
      createDate: "2024-07-22T00:19:00",
      owner: {
        externalId: "2a24c399-7bf0-4b1d-b8d8-4c42eac8f904",
        name: "john82",
        fullName: "John Doe",
        shortName: "JD",
      },
      dealStatus: "ACTIVE",
      tags: [],
      progressStatus: {
        id: 1,
        status: "CLIENTS_IN_PROGRESS",
        label: "Clients in Progress",
        order: 0,
      },
      progressSubStatus: null,
      leads: [
        {
          id: "L2852",
          name: "ლაურსაბ თათქარიძე",
          personalId: "12345678910",
          mobilePhone: "512345678",
          channel: "bbcredit",
          product: "სამომხმარებლო სესხი",
          amount: 177000,
          ccy: "GEL",
          createDate: "2024-07-22T00:19:00",
        },
      ],
    },
    {
      id: "D2060",
      name: "ლაურსაბ თათქარიძე",
      personalId: "12345678910",
      mobilePhone: "512345678",
      channel: "bbcredit",
      product: "სამომხმარებლო სესხი",
      amount: 177000,
      ccy: "GEL",
      comment: null,
      createDate: "2024-07-22T00:19:00",
      owner: {
        externalId: "2a24c399-7bf0-4b1d-b8d8-4c42eac8f904",
        name: "john82",
        fullName: "John Doe",
        shortName: "JD",
      },
      dealStatus: "ACTIVE",
      tags: [],
      progressStatus: {
        id: 1,
        status: "CLIENTS_IN_PROGRESS",
        label: "Clients in Progress",
        order: 0,
      },
      progressSubStatus: null,
      leads: [
        {
          id: "L2852",
          name: "ლაურსაბ თათქარიძე",
          personalId: "12345678910",
          mobilePhone: "512345678",
          channel: "bbcredit",
          product: "სამომხმარებლო სესხი",
          amount: 177000,
          ccy: "GEL",
          createDate: "2024-07-22T00:19:00",
        },
      ],
    },
    {
      id: "D2058",
      name: "ლაურსაბ თათქარიძე",
      personalId: "12345678910",
      mobilePhone: "512345678",
      channel: "bbcredit",
      product: "სამომხმარებლო სესხი",
      amount: 177000,
      ccy: "GEL",
      comment: null,
      createDate: "2024-07-22T00:19:00",
      owner: {
        externalId: "2a24c399-7bf0-4b1d-b8d8-4c42eac8f904",
        name: "john82",
        fullName: "John Doe",
        shortName: "JD",
      },
      dealStatus: "ACTIVE",
      tags: [],
      progressStatus: {
        id: 1,
        status: "CLIENTS_IN_PROGRESS",
        label: "Clients in Progress",
        order: 0,
      },
      progressSubStatus: null,
      leads: [
        {
          id: "L2852",
          name: "ლაურსაბ თათქარიძე",
          personalId: "12345678910",
          mobilePhone: "512345678",
          channel: "bbcredit",
          product: "სამომხმარებლო სესხი",
          amount: 177000,
          ccy: "GEL",
          createDate: "2024-07-22T00:19:00",
        },
      ],
    },
  ],
  totalElements: 25,
  totalPages: 25,
};
